version: "3.3"
services:
  shadowsocks_test:
    container_name: shadowsocks_test
    image: ghcr.io/antyung88/shadowsocks:main
    restart: always
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=password
